name: Deploy

on:
  push:
    branches:
      - main

  repository_dispatch:
    types: [publish-event]

  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build & Deploy Static Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Dependencies
        run: yarn install

      - name: Build the Site
        run: yarn build
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_ENVIRONMENT: master
          CONTENTFUL_HOST: cdn.contentful.com
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}

      - name: Validate AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync Gatsby build to S3
        run: |
          aws s3 sync public s3://brandonwkipp.com --cache-control public,max-age=0,must-revalidate --include "*" --exclude "*.js" --exclude "*.css" --exclude "static/*" --include "sw.js" --delete
          aws s3 sync public s3://brandonwkipp.com --cache-control public,max-age=31536000,immutable --exclude "*" --include "*.js" --include "*.css" --include "static/*" --exclude "sw.js" --delete

      - name: Invalidate Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID}} --paths "/*"